---
on:
  push:
    paths:
      - VERSION

jobs:
  set-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Readme
        uses: ./
        with:
          FILE: README.md
          PATTERN: (udondan/verdoc\@v)[0-9.]+
          REPLACE: \${1}${VERSION}

      - name: Diff
        run: git diff --exit-code
        continue-on-error: true

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updates version references" -a
        if: success()

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
